
# Joint order: head, neck, r_shoulder, r_elbow, r_wrist, l_shoulder, l_elbow, l_wrist,
#              r_hip, r_knee, r_ankle, l_hip, l_knee, l_ankle
# All coords are relative to center (0,0), scaled to canvas size at draw time

POSES = {
    "idle": {
        "head":       (0,   -90),
        "neck":       (0,   -70),
        "r_shoulder": (20,  -60),
        "r_elbow":    (30,  -30),
        "r_wrist":    (25,    5),
        "l_shoulder": (-20, -60),
        "l_elbow":    (-30, -30),
        "l_wrist":    (-25,   5),
        "r_hip":      (12,  -10),
        "r_knee":     (14,   30),
        "r_ankle":    (12,   70),
        "l_hip":      (-12, -10),
        "l_knee":     (-14,  30),
        "l_ankle":    (-12,  70),
    },
    "run_a": {
        "head":       (0,   -90),
        "neck":       (0,   -70),
        "r_shoulder": (20,  -60),
        "r_elbow":    (40,  -20),
        "r_wrist":    (50,   10),
        "l_shoulder": (-20, -60),
        "l_elbow":    (-40, -40),
        "l_wrist":    (-50, -10),
        "r_hip":      (12,  -10),
        "r_knee":     (30,   20),
        "r_ankle":    (20,   60),
        "l_hip":      (-12, -10),
        "l_knee":     (-20,  10),
        "l_ankle":    (-30,  60),
    },
    "run_b": {
        "head":       (0,   -90),
        "neck":       (0,   -70),
        "r_shoulder": (20,  -60),
        "r_elbow":    (40,  -40),
        "r_wrist":    (50,  -10),
        "l_shoulder": (-20, -60),
        "l_elbow":    (-40, -20),
        "l_wrist":    (-50,  10),
        "r_hip":      (12,  -10),
        "r_knee":     (20,   10),
        "r_ankle":    (30,   60),
        "l_hip":      (-12, -10),
        "l_knee":     (-30,  20),
        "l_ankle":    (-20,  60),
    },
    "jump_crouch": {
        "head":       (0,   -80),
        "neck":       (0,   -60),
        "r_shoulder": (20,  -50),
        "r_elbow":    (35,  -20),
        "r_wrist":    (30,   10),
        "l_shoulder": (-20, -50),
        "l_elbow":    (-35, -20),
        "l_wrist":    (-30,  10),
        "r_hip":      (15,  -10),
        "r_knee":     (25,   20),
        "r_ankle":    (18,   50),
        "l_hip":      (-15, -10),
        "l_knee":     (-25,  20),
        "l_ankle":    (-18,  50),
    },
    "jump_peak": {
        "head":       (0,   -100),
        "neck":       (0,    -80),
        "r_shoulder": (20,   -70),
        "r_elbow":    (50,   -50),
        "r_wrist":    (60,   -20),
        "l_shoulder": (-20,  -70),
        "l_elbow":    (-50,  -50),
        "l_wrist":    (-60,  -20),
        "r_hip":      (12,   -20),
        "r_knee":     (20,    10),
        "r_ankle":    (15,    45),
        "l_hip":      (-12,  -20),
        "l_knee":     (-20,   10),
        "l_ankle":    (-15,   45),
    },
    "land": {
        "head":       (0,   -75),
        "neck":       (0,   -55),
        "r_shoulder": (25,  -45),
        "r_elbow":    (40,  -15),
        "r_wrist":    (40,   15),
        "l_shoulder": (-25, -45),
        "l_elbow":    (-40, -15),
        "l_wrist":    (-40,  15),
        "r_hip":      (18,  -5),
        "r_knee":     (30,   25),
        "r_ankle":    (22,   60),
        "l_hip":      (-18, -5),
        "l_knee":     (-30,  25),
        "l_ankle":    (-22,  60),
    },
    "punch_windup": {
        "head":       (5,   -90),
        "neck":       (5,   -70),
        "r_shoulder": (25,  -60),
        "r_elbow":    (0,   -40),
        "r_wrist":    (-20, -20),
        "l_shoulder": (-15, -60),
        "l_elbow":    (-25, -30),
        "l_wrist":    (-30,   0),
        "r_hip":      (12,  -10),
        "r_knee":     (14,   30),
        "r_ankle":    (12,   70),
        "l_hip":      (-12, -10),
        "l_knee":     (-14,  30),
        "l_ankle":    (-12,  70),
    },
    "punch_extend": {
        "head":       (5,   -90),
        "neck":       (5,   -70),
        "r_shoulder": (20,  -60),
        "r_elbow":    (45,  -55),
        "r_wrist":    (75,  -50),
        "l_shoulder": (-15, -60),
        "l_elbow":    (-25, -30),
        "l_wrist":    (-30,   0),
        "r_hip":      (12,  -10),
        "r_knee":     (14,   30),
        "r_ankle":    (12,   70),
        "l_hip":      (-12, -10),
        "l_knee":     (-14,  30),
        "l_ankle":    (-12,  70),
    },
    "kick_raise": {
        "head":       (0,   -90),
        "neck":       (0,   -70),
        "r_shoulder": (20,  -60),
        "r_elbow":    (30,  -30),
        "r_wrist":    (25,    5),
        "l_shoulder": (-20, -60),
        "l_elbow":    (-45, -40),
        "l_wrist":    (-60, -20),
        "r_hip":      (12,  -10),
        "r_knee":     (14,   30),
        "r_ankle":    (12,   70),
        "l_hip":      (-12, -10),
        "l_knee":     (-30,  10),
        "l_ankle":    (-20,  40),
    },
    "kick_extend": {
        "head":       (0,   -90),
        "neck":       (0,   -70),
        "r_shoulder": (20,  -60),
        "r_elbow":    (30,  -30),
        "r_wrist":    (25,    5),
        "l_shoulder": (-20, -60),
        "l_elbow":    (-45, -40),
        "l_wrist":    (-60, -20),
        "r_hip":      (12,  -10),
        "r_knee":     (14,   30),
        "r_ankle":    (12,   70),
        "l_hip":      (-12, -10),
        "l_knee":     (-50,  -20),
        "l_ankle":    (-80,  -30),
    },
    "dodge_left": {
        "head":       (-15, -90),
        "neck":       (-10, -70),
        "r_shoulder": (15,  -60),
        "r_elbow":    (20,  -30),
        "r_wrist":    (15,    5),
        "l_shoulder": (-25, -60),
        "l_elbow":    (-35, -30),
        "l_wrist":    (-30,   5),
        "r_hip":      (8,   -10),
        "r_knee":     (10,   30),
        "r_ankle":    (8,    70),
        "l_hip":      (-16, -10),
        "l_knee":     (-18,  30),
        "l_ankle":    (-16,  70),
    },
    "spin_a": {
        "head":       (10,  -90),
        "neck":       (8,   -70),
        "r_shoulder": (30,  -55),
        "r_elbow":    (55,  -45),
        "r_wrist":    (70,  -30),
        "l_shoulder": (-10, -65),
        "l_elbow":    (-20, -35),
        "l_wrist":    (-15,   0),
        "r_hip":      (15,  -10),
        "r_knee":     (20,   25),
        "r_ankle":    (15,   65),
        "l_hip":      (-10, -10),
        "l_knee":     (-40,  10),
        "l_ankle":    (-65, -10),
    },
    "death_fall": {
        "head":       (60,   20),
        "neck":       (45,   10),
        "r_shoulder": (30,    0),
        "r_elbow":    (50,  -15),
        "r_wrist":    (70,  -10),
        "l_shoulder": (20,   15),
        "l_elbow":    (35,   30),
        "l_wrist":    (55,   35),
        "r_hip":      (15,   25),
        "r_knee":     (30,   40),
        "r_ankle":    (50,   45),
        "l_hip":      (5,    30),
        "l_knee":     (20,   55),
        "l_ankle":    (40,   60),
    },
}

MOVE_SEQUENCES = {
    "idle":   [("idle", 30)],
    "run":    [("run_a", 8), ("run_b", 8)] * 3,
    "jump":   [("jump_crouch", 6), ("jump_peak", 10), ("land", 8), ("idle", 6)],
    "land":   [("land", 10), ("idle", 8)],
    "punch":  [("punch_windup", 5), ("punch_extend", 6), ("idle", 8)],
    "kick":   [("kick_raise", 6), ("kick_extend", 7), ("idle", 8)],
    "dodge":  [("dodge_left", 8), ("idle", 6)],
    "spin":   [("spin_a", 8), ("idle", 10)],
    "death":  [("death_fall", 20)],
}
