
import math
from PIL import Image, ImageDraw

# All joint coords: (x, y) relative to center
# Positive Y = down, Negative Y = up
# Scale ~1.0 maps to pixels on a 600x500 canvas

JOINTS = [
    "head", "neck",
    "r_shoulder", "r_elbow", "r_wrist",
    "l_shoulder", "l_elbow", "l_wrist",
    "torso_mid", "torso_low",
    "r_hip", "r_knee", "r_ankle", "r_toe",
    "l_hip", "l_knee", "l_ankle", "l_toe",
]

LIMBS = [
    ("neck",       "r_shoulder"),
    ("neck",       "l_shoulder"),
    ("r_shoulder", "r_elbow"),
    ("r_elbow",    "r_wrist"),
    ("l_shoulder", "l_elbow"),
    ("l_elbow",    "l_wrist"),
    ("neck",       "torso_mid"),
    ("torso_mid",  "torso_low"),
    ("torso_low",  "r_hip"),
    ("torso_low",  "l_hip"),
    ("r_hip",      "r_knee"),
    ("r_knee",     "r_ankle"),
    ("r_ankle",    "r_toe"),
    ("l_hip",      "l_knee"),
    ("l_knee",     "l_ankle"),
    ("l_ankle",    "l_toe"),
]

def _p(x, y):
    return (float(x), float(y))

POSES = {
    "idle": {
        "head":       _p(  0, -110),
        "neck":       _p(  0,  -82),
        "r_shoulder": _p( 28,  -72),
        "r_elbow":    _p( 38,  -38),
        "r_wrist":    _p( 32,   -4),
        "l_shoulder": _p(-28,  -72),
        "l_elbow":    _p(-38,  -38),
        "l_wrist":    _p(-32,   -4),
        "torso_mid":  _p(  0,  -48),
        "torso_low":  _p(  0,  -16),
        "r_hip":      _p( 16,  -10),
        "r_knee":     _p( 20,   32),
        "r_ankle":    _p( 16,   74),
        "r_toe":      _p( 28,   80),
        "l_hip":      _p(-16,  -10),
        "l_knee":     _p(-20,   32),
        "l_ankle":    _p(-16,   74),
        "l_toe":      _p(-28,   80),
    },
    "idle_breath": {
        "head":       _p(  0, -113),
        "neck":       _p(  0,  -85),
        "r_shoulder": _p( 30,  -74),
        "r_elbow":    _p( 40,  -40),
        "r_wrist":    _p( 34,   -6),
        "l_shoulder": _p(-30,  -74),
        "l_elbow":    _p(-40,  -40),
        "l_wrist":    _p(-34,   -6),
        "torso_mid":  _p(  0,  -50),
        "torso_low":  _p(  0,  -18),
        "r_hip":      _p( 16,  -10),
        "r_knee":     _p( 20,   32),
        "r_ankle":    _p( 16,   74),
        "r_toe":      _p( 28,   80),
        "l_hip":      _p(-16,  -10),
        "l_knee":     _p(-20,   32),
        "l_ankle":    _p(-16,   74),
        "l_toe":      _p(-28,   80),
    },
    "run_a": {
        "head":       _p(  4, -108),
        "neck":       _p(  4,  -80),
        "r_shoulder": _p( 30,  -70),
        "r_elbow":    _p( 55,  -48),
        "r_wrist":    _p( 65,  -20),
        "l_shoulder": _p(-22,  -72),
        "l_elbow":    _p(-50,  -52),
        "l_wrist":    _p(-60,  -28),
        "torso_mid":  _p(  2,  -48),
        "torso_low":  _p(  2,  -16),
        "r_hip":      _p( 18,  -10),
        "r_knee":     _p( 36,   22),
        "r_ankle":    _p( 24,   60),
        "r_toe":      _p( 38,   68),
        "l_hip":      _p(-14,  -10),
        "l_knee":     _p(-24,   14),
        "l_ankle":    _p(-36,   58),
        "l_toe":      _p(-48,   60),
    },
    "run_b": {
        "head":       _p( -4, -108),
        "neck":       _p( -4,  -80),
        "r_shoulder": _p( 22,  -72),
        "r_elbow":    _p( 50,  -52),
        "r_wrist":    _p( 60,  -28),
        "l_shoulder": _p(-30,  -70),
        "l_elbow":    _p(-55,  -48),
        "l_wrist":    _p(-65,  -20),
        "torso_mid":  _p( -2,  -48),
        "torso_low":  _p( -2,  -16),
        "r_hip":      _p( 14,  -10),
        "r_knee":     _p( 24,   14),
        "r_ankle":    _p( 36,   58),
        "r_toe":      _p( 48,   60),
        "l_hip":      _p(-18,  -10),
        "l_knee":     _p(-36,   22),
        "l_ankle":    _p(-24,   60),
        "l_toe":      _p(-38,   68),
    },
    "jump_crouch": {
        "head":       _p(  0, -100),
        "neck":       _p(  0,  -74),
        "r_shoulder": _p( 28,  -64),
        "r_elbow":    _p( 44,  -36),
        "r_wrist":    _p( 40,  -10),
        "l_shoulder": _p(-28,  -64),
        "l_elbow":    _p(-44,  -36),
        "l_wrist":    _p(-40,  -10),
        "torso_mid":  _p(  0,  -42),
        "torso_low":  _p(  0,  -12),
        "r_hip":      _p( 20,   -6),
        "r_knee":     _p( 36,   28),
        "r_ankle":    _p( 24,   58),
        "r_toe":      _p( 36,   64),
        "l_hip":      _p(-20,   -6),
        "l_knee":     _p(-36,   28),
        "l_ankle":    _p(-24,   58),
        "l_toe":      _p(-36,   64),
    },
    "jump_rise": {
        "head":       _p(  0, -118),
        "neck":       _p(  0,  -90),
        "r_shoulder": _p( 32,  -80),
        "r_elbow":    _p( 58,  -68),
        "r_wrist":    _p( 72,  -50),
        "l_shoulder": _p(-32,  -80),
        "l_elbow":    _p(-58,  -68),
        "l_wrist":    _p(-72,  -50),
        "torso_mid":  _p(  0,  -58),
        "torso_low":  _p(  0,  -26),
        "r_hip":      _p( 16,  -20),
        "r_knee":     _p( 28,   10),
        "r_ankle":    _p( 20,   44),
        "r_toe":      _p( 30,   50),
        "l_hip":      _p(-16,  -20),
        "l_knee":     _p(-28,   10),
        "l_ankle":    _p(-20,   44),
        "l_toe":      _p(-30,   50),
    },
    "jump_peak": {
        "head":       _p(  0, -122),
        "neck":       _p(  0,  -94),
        "r_shoulder": _p( 34,  -84),
        "r_elbow":    _p( 62,  -78),
        "r_wrist":    _p( 78,  -62),
        "l_shoulder": _p(-34,  -84),
        "l_elbow":    _p(-62,  -78),
        "l_wrist":    _p(-78,  -62),
        "torso_mid":  _p(  0,  -62),
        "torso_low":  _p(  0,  -30),
        "r_hip":      _p( 18,  -24),
        "r_knee":     _p( 32,    2),
        "r_ankle":    _p( 22,   36),
        "r_toe":      _p( 34,   42),
        "l_hip":      _p(-18,  -24),
        "l_knee":     _p(-32,    2),
        "l_ankle":    _p(-22,   36),
        "l_toe":      _p(-34,   42),
    },
    "land": {
        "head":       _p(  0,  -96),
        "neck":       _p(  0,  -70),
        "r_shoulder": _p( 32,  -58),
        "r_elbow":    _p( 50,  -28),
        "r_wrist":    _p( 48,    2),
        "l_shoulder": _p(-32,  -58),
        "l_elbow":    _p(-50,  -28),
        "l_wrist":    _p(-48,    2),
        "torso_mid":  _p(  0,  -38),
        "torso_low":  _p(  0,   -8),
        "r_hip":      _p( 22,   -2),
        "r_knee":     _p( 40,   30),
        "r_ankle":    _p( 28,   64),
        "r_toe":      _p( 40,   70),
        "l_hip":      _p(-22,   -2),
        "l_knee":     _p(-40,   30),
        "l_ankle":    _p(-28,   64),
        "l_toe":      _p(-40,   70),
    },
    "punch_ready": {
        "head":       _p(  6, -110),
        "neck":       _p(  4,  -82),
        "r_shoulder": _p( 24,  -72),
        "r_elbow":    _p(  4,  -54),
        "r_wrist":    _p( -8,  -34),
        "l_shoulder": _p(-24,  -72),
        "l_elbow":    _p(-40,  -44),
        "l_wrist":    _p(-44,  -18),
        "torso_mid":  _p(  2,  -50),
        "torso_low":  _p(  2,  -18),
        "r_hip":      _p( 18,  -12),
        "r_knee":     _p( 24,   30),
        "r_ankle":    _p( 18,   72),
        "r_toe":      _p( 30,   78),
        "l_hip":      _p(-14,  -12),
        "l_knee":     _p(-18,   30),
        "l_ankle":    _p(-14,   72),
        "l_toe":      _p(-26,   78),
    },
    "punch_mid": {
        "head":       _p(  8, -110),
        "neck":       _p(  6,  -82),
        "r_shoulder": _p( 26,  -72),
        "r_elbow":    _p( 52,  -62),
        "r_wrist":    _p( 80,  -56),
        "l_shoulder": _p(-20,  -72),
        "l_elbow":    _p(-38,  -44),
        "l_wrist":    _p(-42,  -18),
        "torso_mid":  _p(  3,  -50),
        "torso_low":  _p(  3,  -18),
        "r_hip":      _p( 18,  -12),
        "r_knee":     _p( 24,   30),
        "r_ankle":    _p( 18,   72),
        "r_toe":      _p( 30,   78),
        "l_hip":      _p(-14,  -12),
        "l_knee":     _p(-18,   30),
        "l_ankle":    _p(-14,   72),
        "l_toe":      _p(-26,   78),
    },
    "punch_extend": {
        "head":       _p( 10, -110),
        "neck":       _p(  8,  -82),
        "r_shoulder": _p( 28,  -70),
        "r_elbow":    _p( 58,  -62),
        "r_wrist":    _p( 92,  -56),
        "l_shoulder": _p(-18,  -72),
        "l_elbow":    _p(-36,  -46),
        "l_wrist":    _p(-40,  -20),
        "torso_mid":  _p(  4,  -50),
        "torso_low":  _p(  4,  -18),
        "r_hip":      _p( 20,  -12),
        "r_knee":     _p( 26,   30),
        "r_ankle":    _p( 20,   72),
        "r_toe":      _p( 32,   78),
        "l_hip":      _p(-12,  -12),
        "l_knee":     _p(-16,   30),
        "l_ankle":    _p(-12,   72),
        "l_toe":      _p(-24,   78),
    },
    "kick_load": {
        "head":       _p(  0, -110),
        "neck":       _p(  0,  -82),
        "r_shoulder": _p( 28,  -72),
        "r_elbow":    _p( 44,  -44),
        "r_wrist":    _p( 50,  -18),
        "l_shoulder": _p(-28,  -72),
        "l_elbow":    _p(-44,  -44),
        "l_wrist":    _p(-50,  -18),
        "torso_mid":  _p(  0,  -50),
        "torso_low":  _p(  0,  -18),
        "r_hip":      _p( 16,  -10),
        "r_knee":     _p( 20,   32),
        "r_ankle":    _p( 16,   74),
        "r_toe":      _p( 28,   80),
        "l_hip":      _p(-16,  -10),
        "l_knee":     _p(-34,    8),
        "l_ankle":    _p(-26,   44),
        "l_toe":      _p(-14,   50),
    },
    "kick_extend": {
        "head":       _p(  2, -110),
        "neck":       _p(  2,  -82),
        "r_shoulder": _p( 28,  -72),
        "r_elbow":    _p( 44,  -44),
        "r_wrist":    _p( 50,  -18),
        "l_shoulder": _p(-24,  -72),
        "l_elbow":    _p(-44,  -46),
        "l_wrist":    _p(-52,  -22),
        "torso_mid":  _p(  1,  -50),
        "torso_low":  _p(  1,  -18),
        "r_hip":      _p( 16,  -10),
        "r_knee":     _p( 20,   32),
        "r_ankle":    _p( 16,   74),
        "r_toe":      _p( 28,   80),
        "l_hip":      _p(-16,  -10),
        "l_knee":     _p(-60,  -10),
        "l_ankle":    _p(-96,   -4),
        "l_toe":      _p(-108,   4),
    },
    "dodge_lean": {
        "head":       _p(-20, -108),
        "neck":       _p(-14,  -82),
        "r_shoulder": _p( 16,  -72),
        "r_elbow":    _p( 22,  -42),
        "r_wrist":    _p( 16,  -14),
        "l_shoulder": _p(-34,  -72),
        "l_elbow":    _p(-50,  -46),
        "l_wrist":    _p(-58,  -22),
        "torso_mid":  _p( -8,  -50),
        "torso_low":  _p( -4,  -18),
        "r_hip":      _p( 12,  -12),
        "r_knee":     _p( 16,   30),
        "r_ankle":    _p( 12,   72),
        "r_toe":      _p( 24,   78),
        "l_hip":      _p(-20,  -12),
        "l_knee":     _p(-24,   30),
        "l_ankle":    _p(-20,   72),
        "l_toe":      _p(-32,   78),
    },
    "uppercut_load": {
        "head":       _p( -4, -108),
        "neck":       _p( -2,  -80),
        "r_shoulder": _p( 22,  -70),
        "r_elbow":    _p( 14,  -38),
        "r_wrist":    _p(  6,  -12),
        "l_shoulder": _p(-26,  -72),
        "l_elbow":    _p(-42,  -46),
        "l_wrist":    _p(-48,  -20),
        "torso_mid":  _p( -1,  -48),
        "torso_low":  _p( -1,  -16),
        "r_hip":      _p( 16,  -10),
        "r_knee":     _p( 20,   32),
        "r_ankle":    _p( 16,   74),
        "r_toe":      _p( 28,   80),
        "l_hip":      _p(-16,  -10),
        "l_knee":     _p(-20,   32),
        "l_ankle":    _p(-16,   74),
        "l_toe":      _p(-28,   80),
    },
    "uppercut_extend": {
        "head":       _p(  4, -116),
        "neck":       _p(  2,  -88),
        "r_shoulder": _p( 24,  -78),
        "r_elbow":    _p( 22,  -108),
        "r_wrist":    _p( 18,  -132),
        "l_shoulder": _p(-24,  -74),
        "l_elbow":    _p(-40,  -50),
        "l_wrist":    _p(-46,  -26),
        "torso_mid":  _p(  1,  -56),
        "torso_low":  _p(  1,  -24),
        "r_hip":      _p( 16,  -18),
        "r_knee":     _p( 24,   22),
        "r_ankle":    _p( 18,   62),
        "r_toe":      _p( 30,   68),
        "l_hip":      _p(-16,  -10),
        "l_knee":     _p(-20,   32),
        "l_ankle":    _p(-16,   74),
        "l_toe":      _p(-28,   80),
    },
    "spin_a": {
        "head":       _p( 10, -110),
        "neck":       _p(  8,  -82),
        "r_shoulder": _p( 38,  -68),
        "r_elbow":    _p( 68,  -58),
        "r_wrist":    _p( 88,  -44),
        "l_shoulder": _p(-18,  -76),
        "l_elbow":    _p(-28,  -48),
        "l_wrist":    _p(-22,  -22),
        "torso_mid":  _p(  4,  -50),
        "torso_low":  _p(  4,  -18),
        "r_hip":      _p( 18,  -12),
        "r_knee":     _p( 28,   26),
        "r_ankle":    _p( 18,   68),
        "r_toe":      _p( 30,   74),
        "l_hip":      _p(-12,  -12),
        "l_knee":     _p(-54,   -4),
        "l_ankle":    _p(-88,    0),
        "l_toe":      _p(-100,   8),
    },
    "spin_b": {
        "head":       _p(-10, -110),
        "neck":       _p( -8,  -82),
        "r_shoulder": _p( 18,  -76),
        "r_elbow":    _p( 28,  -48),
        "r_wrist":    _p( 22,  -22),
        "l_shoulder": _p(-38,  -68),
        "l_elbow":    _p(-68,  -58),
        "l_wrist":    _p(-88,  -44),
        "torso_mid":  _p( -4,  -50),
        "torso_low":  _p( -4,  -18),
        "r_hip":      _p( 12,  -12),
        "r_knee":     _p( 54,   -4),
        "r_ankle":    _p( 88,    0),
        "r_toe":      _p(100,    8),
        "l_hip":      _p(-18,  -12),
        "l_knee":     _p(-28,   26),
        "l_ankle":    _p(-18,   68),
        "l_toe":      _p(-30,   74),
    },
    "flip_a": {
        "head":       _p(  0, -120),
        "neck":       _p(  0,  -92),
        "r_shoulder": _p( 30,  -82),
        "r_elbow":    _p( 54,  -68),
        "r_wrist":    _p( 64,  -46),
        "l_shoulder": _p(-30,  -82),
        "l_elbow":    _p(-54,  -68),
        "l_wrist":    _p(-64,  -46),
        "torso_mid":  _p(  0,  -60),
        "torso_low":  _p(  0,  -28),
        "r_hip":      _p( 16,  -22),
        "r_knee":     _p( 20,   12),
        "r_ankle":    _p( 14,   46),
        "r_toe":      _p( 26,   52),
        "l_hip":      _p(-16,  -22),
        "l_knee":     _p(-20,   12),
        "l_ankle":    _p(-14,   46),
        "l_toe":      _p(-26,   52),
    },
    "flip_b": {
        "head":       _p(  0,  -30),
        "neck":       _p(  0,  -58),
        "r_shoulder": _p( 28,  -68),
        "r_elbow":    _p( 46,  -86),
        "r_wrist":    _p( 52, -106),
        "l_shoulder": _p(-28,  -68),
        "l_elbow":    _p(-46,  -86),
        "l_wrist":    _p(-52, -106),
        "torso_mid":  _p(  0,  -40),
        "torso_low":  _p(  0,  -12),
        "r_hip":      _p( 16,   -8),
        "r_knee":     _p( 22,  -44),
        "r_ankle":    _p( 16,  -80),
        "r_toe":      _p( 28,  -86),
        "l_hip":      _p(-16,   -8),
        "l_knee":     _p(-22,  -44),
        "l_ankle":    _p(-16,  -80),
        "l_toe":      _p(-28,  -86),
    },
    "taunt": {
        "head":       _p( -8, -112),
        "neck":       _p( -4,  -84),
        "r_shoulder": _p( 26,  -74),
        "r_elbow":    _p( 48,  -52),
        "r_wrist":    _p( 62,  -30),
        "l_shoulder": _p(-26,  -74),
        "l_elbow":    _p(-30,  -48),
        "l_wrist":    _p(-18,  -28),
        "torso_mid":  _p( -2,  -52),
        "torso_low":  _p( -2,  -20),
        "r_hip":      _p( 14,  -14),
        "r_knee":     _p( 18,   28),
        "r_ankle":    _p( 14,   70),
        "r_toe":      _p( 26,   76),
        "l_hip":      _p(-18,  -14),
        "l_knee":     _p(-22,   28),
        "l_ankle":    _p(-18,   70),
        "l_toe":      _p(-30,   76),
    },
    "death_fall": {
        "head":       _p( 80,   24),
        "neck":       _p( 60,   14),
        "r_shoulder": _p( 42,    4),
        "r_elbow":    _p( 66,  -12),
        "r_wrist":    _p( 86,   -8),
        "l_shoulder": _p( 30,   20),
        "l_elbow":    _p( 50,   36),
        "l_wrist":    _p( 68,   40),
        "torso_mid":  _p( 36,   10),
        "torso_low":  _p( 20,   18),
        "r_hip":      _p( 22,   28),
        "r_knee":     _p( 40,   44),
        "r_ankle":    _p( 58,   50),
        "r_toe":      _p( 70,   44),
        "l_hip":      _p( 10,   32),
        "l_knee":     _p( 26,   60),
        "l_ankle":    _p( 44,   68),
        "l_toe":      _p( 56,   62),
    },
    "guard": {
        "head":       _p(  0, -110),
        "neck":       _p(  0,  -82),
        "r_shoulder": _p( 26,  -72),
        "r_elbow":    _p( 16,  -50),
        "r_wrist":    _p(  4,  -30),
        "l_shoulder": _p(-26,  -72),
        "l_elbow":    _p(-16,  -50),
        "l_wrist":    _p( -4,  -30),
        "torso_mid":  _p(  0,  -50),
        "torso_low":  _p(  0,  -18),
        "r_hip":      _p( 20,  -12),
        "r_knee":     _p( 30,   26),
        "r_ankle":    _p( 22,   66),
        "r_toe":      _p( 34,   72),
        "l_hip":      _p(-20,  -12),
        "l_knee":     _p(-30,   26),
        "l_ankle":    _p(-22,   66),
        "l_toe":      _p(-34,   72),
    },
    "slide": {
        "head":       _p( 20,  -60),
        "neck":       _p( 10,  -40),
        "r_shoulder": _p( 28,  -28),
        "r_elbow":    _p( 52,  -16),
        "r_wrist":    _p( 72,   -4),
        "l_shoulder": _p(  4,  -30),
        "l_elbow":    _p( -8,  -14),
        "l_wrist":    _p(-20,    0),
        "torso_mid":  _p( 14,  -20),
        "torso_low":  _p(  6,   -6),
        "r_hip":      _p( 14,    6),
        "r_knee":     _p( 48,   10),
        "r_ankle":    _p( 82,    8),
        "r_toe":      _p( 96,    2),
        "l_hip":      _p(  0,   10),
        "l_knee":     _p(-10,   38),
        "l_ankle":    _p(  8,   64),
        "l_toe":      _p( 20,   70),
    },
    "walljump": {
        "head":       _p(-50, -110),
        "neck":       _p(-42,  -84),
        "r_shoulder": _p(-18,  -80),
        "r_elbow":    _p(  4,  -96),
        "r_wrist":    _p( 24, -106),
        "l_shoulder": _p(-62,  -78),
        "l_elbow":    _p(-72,  -56),
        "l_wrist":    _p(-64,  -34),
        "torso_mid":  _p(-44,  -60),
        "torso_low":  _p(-38,  -30),
        "r_hip":      _p(-28,  -22),
        "r_knee":     _p(-14,   14),
        "r_ankle":    _p(-22,   50),
        "r_toe":      _p(-10,   56),
        "l_hip":      _p(-46,  -22),
        "l_knee":     _p(-62,   10),
        "l_ankle":    _p(-58,   48),
        "l_toe":      _p(-46,   54),
    },
}

MOVE_SEQUENCES = {
    "idle":      [("idle", 15), ("idle_breath", 15), ("idle", 15), ("idle_breath", 15)],
    "run":       [("run_a", 8), ("run_b", 8)] * 4,
    "jump":      [("idle", 4), ("jump_crouch", 5), ("jump_rise", 6),
                  ("jump_peak", 8), ("jump_rise", 5), ("land", 7), ("idle", 5)],
    "land":      [("land", 10), ("idle", 8)],
    "punch":     [("idle", 3), ("punch_ready", 5), ("punch_mid", 4),
                  ("punch_extend", 5), ("punch_ready", 4), ("idle", 5)],
    "kick":      [("idle", 3), ("kick_load", 5), ("kick_extend", 6),
                  ("kick_load", 4), ("idle", 5)],
    "uppercut":  [("idle", 3), ("uppercut_load", 6), ("uppercut_extend", 6),
                  ("idle", 5)],
    "dodge":     [("idle", 3), ("dodge_lean", 8), ("idle", 6)],
    "spin":      [("idle", 3), ("spin_a", 7), ("spin_b", 7), ("spin_a", 5), ("idle", 5)],
    "flip":      [("jump_crouch", 4), ("flip_a", 7), ("flip_b", 7),
                  ("flip_a", 5), ("land", 6), ("idle", 5)],
    "slide":     [("idle", 3), ("slide", 10), ("idle", 6)],
    "walljump":  [("walljump", 8), ("jump_peak", 6), ("land", 7), ("idle", 5)],
    "taunt":     [("idle", 4), ("taunt", 10), ("idle", 6)],
    "guard":     [("guard", 20)],
    "death":     [("idle", 4), ("jump_crouch", 5), ("death_fall", 20)],
}
